---
- name: set sysctl values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - name: net.core.somaxconn
      value: 65535
    - name: net.ipv4.tcp_max_syn_backlog
      value: 65535
    - name: net.ipv4.tcp_fin_timeout
      value: 20
    - name: net.ipv4.tcp_max_tw_buckets
      value: 1440000
    - name: vm.overcommit_memory
      value: 1
    - name: vm.vfs_cache_pressure
      value: 60
    - name: vm.max_map_count
      value: 262144
    - name: fs.file-max
      value: 1000000
    - name: kernel.pid_max
      value: 65536
    - name: net.ipv4.ip_local_port_range
      value: 10000 65535
    - name: net.ipv4.udp_rmem_min
      value: 8192
    - name: net.ipv4.udp_wmem_min
      value: 8192
    - name: net.ipv4.tcp_syncookies
      value: 1
    - name: fs.nr_open
      value: 10485760

- name: configure max open file number limits
  pam_limits: domain={{ item.domain }} limit_type={{ item.type }} limit_item={{ item.name }} value={{ item.value }}
  with_items:
    - { domain: "*", type: "soft" ,name: "memlock" ,value: "unlimited" }
    - { domain: "*", type: "hard" ,name: "memlock" ,value: "unlimited" }
    - { domain: "*", type: "soft" ,name: "nofile" ,value: "1000000" }
    - { domain: "*", type: "hard" ,name: "nofile" ,value: "1000000" }
    - { domain: "*", type: "soft" ,name: "nproc" ,value: "1000000" }
    - { domain: "*", type: "hard" ,name: "nproc" ,value: "1000000" }

- name: disable kernel.mm.transparent_hugepage debian
  lineinfile:
    dest: '/etc/rc.local'
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag'
    insertbefore: 'exit 0'
  when: is_debian

- name: ensure /etc/rc.d/rc.local
  file: path=/etc/rc.d/rc.local state=touch mode=0755
  when: is_redhat

- name: disable kernel.mm.transparent_hugepage redhat
  lineinfile:
    dest: '/etc/rc.d/rc.local'
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag'
    insertafter: 'will be executed during boot.'
  when: is_redhat

- name: Disable Transparent Huge Pages until reboot
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  ignore_errors: true
